### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by NH603** [amandris/arbitrage-trading-bot#1] opened 2019-01-29 06:46 UTC
Hello, there appears to be a build issue. Based on your knowledge of the code, would you be willing to create a docker-compose.yml/Dockerfile to help build on VM? If not, give me 24 hours to learn code and I’ll submit a PR for us. Thank you in advance for your willingness to help. 

- NH603

**Comment by amandris** [comment] 2019-01-29 11:25
Could you provide a little more information about the build issue? I can fix it up if you need it. But you are welcome to create a Dockerfile if you prefer so.

**Comment by NH603** [comment] 2019-01-29 11:43
Thank you very much Amandris. Yes, confronting an issue when trying to run the following command to create database “bin/console doctrine:schema:update --force”. I can attach error message if helpful, but that’s why I thought perhaps containerizing with Docker to support db creation, etc would be a quick fix.

I’ll be standing by ready to help. Thanks again

**Comment by amandris** [comment] 2019-01-29 12:46
Yes, attach error message, please. Maybe I forgot some steps on the **Installation** _Readme.md_ section.

**Comment by NH603** [comment] 2019-01-29 15:24
Hi Amandris,

Yes, please find the error message copied below when entering the command to create database in the Installation Readme.md section. Please let me know if you have any recommendations? Thank you again.

"In AbstractMySQLDriver.php line 93:

  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 31:

  SQLSTATE[HY000] [2002] Connection refused


In PDOConnection.php line 27:

  SQLSTATE[HY000] [2002] Connection refused"

**Comment by amandris** [comment] 2019-01-29 15:38
Remember to check the database settings are correct in the **parameters.yml** file. 

Also check the `database_driver` is `pdo_mysql`. 

The database must be previously created. If you didn't create it manually try to run **php bin/console doctrine:database:create** before **the bin/console doctrine:schema:update --force** command.

**Comment by NH603** [comment] 2019-01-29 19:05
Thank you for the quick reply Amandris. It’s very much appreciated; especially when I’m eager to test your extremely impressive app. Unfortunately, still receiving same error when trying steps above. Perhaps, it’s a dependency/extension issue and I’m missing some dependency requirements? 

Thanks again for all your support.

**Comment by NH603** [comment] 2019-01-29 21:06
Thank you Amandris. I've included the text from the parameters.yml below. Note: running in a DO VM.  Based on your review, perhaps, I try with Postgress instead? 

#app/config/parameters.yml
    database_driver: pdo_mysql
    database_host: 167.99.168.129
    database_port: 3306
    database_name: arbitrage_trading_bot
    database_user: app
    database_password: null
    database_charset: utf8mb4

Thanks again, and I'll be standing by.

**Comment by NH603** [comment] 2019-01-30 02:47
Hello Amandris, I've tried with Postgres as well and database build still does not through with the commands above. Do you perhaps have any helpful suggestions? I'm not sure if you're familiar with docker-compose.yml? But that may be a good option for building symfony, app and database. 

Thanks again, and I'll be standing by.

**Comment by amandris** [comment] 2019-01-30 12:55
Maybe the problem is in the **database_password: null** parameter. Have you tried to set a password in your DB. Maybe the symfony orm is trying to log in with **"null"** as password.

**Comment by mgmerino** [comment] 2019-01-30 13:52
Hello @NH603, I could wrap this as a Docker container for deploying it easily, but I would need a couple of days to sort it out. If you can wait, I'll ping you when it's ready.

**Comment by NH603** [comment] 2019-01-30 15:55
Hi Manu,

It’s good to hear from you, and yes, that would be extremely helpful! Thank you for your willingness to support with Docker. It’s really much appreciated.

I’ve been still tweaking the database configurations, but to no avail. So based on my DO VM setup, I think Docker may be the easiest option. I’ve been trying to get this repo, which provides a good symfony docker-compose bootstrap foundation, to build and launch the arbitrage-trading-bot. I’m close, but still haven’t got it to all work yet. https://github.com/eko/docker-symfony/blob/master/README.md

**Comment by NH603** [comment] 2019-02-03 04:15
I’m still struggling to get app to launch. Whether in Docker or locally. Can you perhaps share node_modules and var/www folders or as much as you can? Any help would be much appreciated.

Thanks again

**Comment by amandris** [comment] 2019-02-03 11:48
**node_modules** directory is created when running `npm install`. Do you still get the` SQLSTATE[HY000] [2002] Connection refused` error? if so, I think you still have a DB connection issue (not related to the project). If you get any new error message when deploying, please let me know.

**Comment by NH603** [comment] 2019-02-05 04:50
Hi Amandris, 
Thank you for the reply. Good news, I was successful in getting the application to load! 

However, when entering in the following command, I received a response about "No key/secret.." - see copy from command line below. Is this intended? I used the default  secret you originally had shared in parameters.yml.dist. 

"app@XXXXXX:~/directory/app$ bin/console bot:trade
No key/secret/client_idapp@XXXXXX:~/directory/app"

Also, I had enable Binance as the first exchange. Does it take awhile for the Ticker & Differences to populate with api info? 

Thanks for all the support! I'm excited to actually start using this.

**Comment by NH603** [comment] 2019-02-05 06:33
Hi Amandris, 

I was successful in getting the "bin/console bot:trade" command to work, and while the "Ticker" now populates in the app, I'm receiving the following error once the command is inserted into the command line. Do you have any recommendations on how to resolve? 

"app@XXXXXX:~/directory/app$ bin/console bot:trade
05/02/2019 07:29:59
    bitstamp   Ask:3,418.07  Bid:3,418.06
    okcoin     Ask:3,416.03  Bid:3,417.72
    binance    Ask:3,465.98  Bid:3,465.95

In ItbitService.php line 148:

Cannot use object of type stdClass as array"

Thank you in advance for your help on this!

**Comment by amandris** [comment] 2019-02-05 08:48
I close this issue and create a new one with your last message.

**Closed by amandris** 2019-02-05 08:48 UTC

**Comment by xazes** [comment] 2020-09-19 12:00
Hi
I have the same problem:
 bin/console bot:trade result in No key/secret/client_id

I have set enable: false by bitstamp on config.yml
